# Welcome to Jekyll!
#
# This config file contains settings that affect your entire blog.
# If you find yourself editing this file frequently, consider using Jekyll's data files
# for the data you need to update often.
#
# Note: This file is *NOT* automatically reloaded when running 'bundle exec jekyll serve'.
# Restart the server process after making changes.

# References for YAML syntax:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

# Site settings
title: "Technology Insights from Various Books"
email: "bs.mahi@gmail.com"
description: >-
  Writing about the tech insights from various books that I have been reading.
baseurl: "/" # The subpath of your site (e.g., "/blog" for example.com/blog)
url: "https://bsmlabs.github.io" # The base hostname & protocol for your site

# Build settings
theme: minima

author:
  name: "Mahendra Rao B"
  email: "bs.mahi@gmail.com"

minima:
  skin: dark
  social_links:
    github: "bsmahi"

plugins:
  - jekyll-feed
  # - jekyll-paginate

show_excerpts: true
# paginate: false

# Exclude from processing
# The following directories and files will not be processed by Jekyll.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
