# Site settings
title: "Tech Books Insights"
email: "bs.mahi@gmail.com"
description: >-
  Exploring technical concepts and insights from books that I read.
baseurl: "/tech-books-insights"  # The subpath for GitHub Pages
url: "https://bsmahi.github.io"  # Your GitHub Pages URL

# Author information
author:
  name: "Mahendra Rao B"
  email: "bs.mahi@gmail.com"

# Theme settings
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: dark  # Other options: default, air, aqua, etc.

# Navigation
nav:
  - title: "Home"
    url: /
  - title: "ArchitecturePatterns"
    url: /ArchitecturePatterns/
  - title: "Book Reviews"
    url: /books/
  - title: "Categories"
    url: /categories/
  - title: "Tags"
    url: /tags/
  - title: "About"
    url: /about/

# Social Links
social:
  github: bsmahi
  linkedin: your-linkedin-handle
  twitter: your-twitter-handle

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Markdown & Syntax Highlighting
markdown: kramdown
highlighter: rouge

# Exclude unnecessary files from processing
exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md
